### ISSUE TITLE
Add sound alert

### ISSUE THREAD

**Issue by svenke7** [amerryma/alt1-bik-proc-timer#1]
Would it be possible to have alerts trigger on configurable times?

**Comment by amerryma** [comment]
What sort of configurability would you like to see with sounds?

**Comment by svenke7** [comment]
Similar to the afk alerter.
So 2 which can be set at which time to trigger which alert. So you can for instance set up to play Alert A at 55 and Alert B at 05. Both should be optional of course since not everybody wants any alerts or some only want the before or after alert.

**Comment by amerryma** [comment]
I've added this. Let me know what you think!

**Comment by svenke7** [comment]
Would it be possible to make them configurable like AFK Warden or would that require you adding all the alerts they use? Was hoping they would be included in base alt1.

Would also be nice if you can enable only the before timer and not both for example.

**Comment by amerryma** [comment]
Unfortunately I don't have any access to the code for the afkwarden so it'd
be too much work to add it all myself.
